### ISSUE TITLE
Building a static library of xs6 runtime

### ISSUE THREAD

**Issue by iamtakingiteasy** [Kinoma/kinomajs#29]
Hi, I am trying to build a static library with kinoma implementation of ES6 javascript engine for embedding into my application, but don't quite understand how to do that: I see `xs6/sources/fsk/xs6Host.c` is the only file containing implementation of `fxNewMachine` API function, but could not see it being compiled or referenced in any way in any of CMake scripts, so it is never gets included into any library being built by cmake. What I am missing?

**Comment by archite** [comment]
Which architecture are you using?

Sent from my iPhone

On Mar 23, 2018, at 12:11 AM, Alexander Tumin <notifications@github.com>
wrote:

Hi, I am trying to build a static library with kinoma implementation of ES6
javascript engine for embedding into my application, but don't quite
understand how to do that: I see xs6/sources/fsk/xs6Host.c is the only file
containing implementation of fxNewMachine API function, but could not see
it being compiled or referenced in any way in any of CMake scripts, so it
is never gets included into any library being built by cmake. What I am
missing?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Kinoma/kinomajs/issues/29>, or mute the thread

**Comment by iamtakingiteasy** [comment]
My target OS'es are x86_64 POSIX/Linux and Windows 7+

**Comment by phoddie** [comment]
@iamtakingiteasy - As noted on a couple of other issues, this repository is no longer maintained. Marvell Semiconductor has decided not to continue support for Kinoma. @archite may well be able to help you with build issues here, as he created the build system for this repository. However, for any serious work, I suggest transitioning to the most recent version of the XS JavaScript engine, maintained by Moddable. It supports the most recent, as of this writing, version of the JavaScript language specification. It is hosted [here](https://github.com/Moddable-OpenSource/moddable) on GitHub.

**Comment by iamtakingiteasy** [comment]
Many thanks to you, i will try building moddable.
